apiVersion: openebs.io/v1alpha1
kind: BlockDevice
metadata:
 name: blockdevice-0345c8f2-2a0d-4750-bd9a-6ae8b0f67870
 labels:
   kubernetes.io/hostname: penetanguishene
   ndm.io/managed: "false"
   ndm.io/blockdevice-type: blockdevice
status:
 claimState: Unclaimed
 state: Active
spec:
 capacity:
   logicalSectorSize: 512
   storage: 107374182400
 details:
   deviceType: lvm
 devlinks:
 - kind: by-id
   links:
   - /dev/disk/by-id/dm-uuid-LVM-z8cgaSUf9dfEfgTAIkuNgh1sa7P7m2vaUnfe8Im7dlOowRWpzGICm0do1dLFdp8N
   - /dev/disk/by-id/dm-name-ubuntu--vg-iscsi--lv
 - kind: by-path
   links:
   - /dev/mapper/ubuntu--vg-iscsi--lv
 nodeAttributes:
   nodeName: penetanguishene
 path: /dev/dm-1
---
apiVersion: openebs.io/v1alpha1
kind: BlockDevice
metadata:
  name: blockdevice-5d53a7fe-956e-448b-a93e-de4032a169c8
  labels:
    kubernetes.io/hostname: sudbury
    ndm.io/managed: "false"
    ndm.io/blockdevice-type: blockdevice
status:
  claimState: Unclaimed
  state: Active
spec:
  capacity:
    logicalSectorSize: 512
    storage: 107374182400
  details:
    deviceType: lvm
  devlinks:
  - kind: by-id
    links:
    - /dev/disk/by-id/dm-uuid-LVM-ChXmpOd3oI13ONp3ueiapR3GVHWYdzOyjuLNnAGLkcyOHNN6lFLH7URTLMwXGlY2
    - /dev/disk/by-id/dm-name-ubuntu--vg-iscsi--lv
  - kind: by-path
    links:
    - /dev/mapper/ubuntu--vg-iscsi--lv
  nodeAttributes:
    nodeName: sudbury
  path: /dev/dm-1
---
