#Use the following YAMLs to create a cStor Storage Pool.
apiVersion: openebs.io/v1alpha1
kind: StoragePoolClaim
metadata:
  name: cstor-disk-pool
  annotations:
    cas.openebs.io/config: |
      - name: PoolResourceRequests
        value: |-
            memory: 2Gi
      - name: PoolResourceLimits
        value: |-
            memory: 4Gi
spec:
  name: cstor-disk-pool
  type: disk
  poolSpec:
    poolType: striped
  blockDevices:
    blockDeviceList:
    - blockdevice-0677cb25-01d4-4b7f-b318-77a98705173a
    - blockdevice-6d4ac653-4833-4b98-aad6-17ef1d013ca6
    - blockdevice-71e4198b-be2b-41f1-aa58-b21c3e57809c
---
